### ISSUE TITLE
Cannot set favorites on a different drive (Windows)

### ISSUE THREAD

**Issue by jat255** [raguay/favorites#2]
My fman and user profile live on the `C:` drive, and if I try to add a favorite on my data drive (`D:`), I receive the following error:

```
Command 'SetFavoriteDirectory' raised exception.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 108, in _run_in_thread
  File "C:\Users\jat\AppData\Roaming\fman\Plugins\Third-party\favorites\favorites\__init__.py", line 196, in __call__
    dirName = shortenDirPath(dirName)
  File "C:\Users\jat\AppData\Roaming\fman\Plugins\Third-party\favorites\favorites\__init__.py", line 284, in shortenDirPath
    if path_is_parent(os.path.expanduser("~"),dirName):
  File "C:\Users\jat\AppData\Roaming\fman\Plugins\Third-party\favorites\favorites\__init__.py", line 297, in path_is_parent
    return os.path.commonpath([parent_path]) == os.path.commonpath([parent_path, child_path])
  File "ntpath.py", line 632, in commonpath
ValueError: Paths don't have the same drive
```

**Comment by raguay** [comment]
Okay. Sorry about the problem, but I currently do not have a Windows system
to debug this issue. I'm currently traveling in the US and my Windows
system is in Thailand. As soon as I can, I'll try to figure out how to fix
it.

**Comment by raguay** [comment]
Should work now.
