### ISSUE TITLE
Not working with new version on OSX

### ISSUE THREAD

**Issue by NvL-WEAP** [raguay/favorites#3]
Since the new release 0.7.4 the favorites plugin isn't working anymore. Probably due the change of path structure and added zip feature.

> Previously, files were located by their path, say C:\test.txt. This has now become file://C:/test.txt.

installation error:
```
Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 270, in _run_in_thread
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1165, in __call__
    dest_dir = self._install_plugin(repo.name, zipball_contents)
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1199, in _install_plugin
    dir_in_zip, = iterdir(zip_url)
  File "fman/impl/util/__init__.py", line 137, in __next__
  File "fman/impl/util/__init__.py", line 114, in get_next
  File "fman/impl/util/__init__.py", line 118, in _generate_next
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 46, in iterdir
    for candidate in self._iter_names(zip_path, path_in_zip):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 235, in _iter_names
    for file_info in self._iter_infos(zip_path, path_in_zip):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 247, in _iter_infos
    raise filenotfounderror(url)
FileNotFoundError: [Errno 2] No such file or directory: 'zip:///var/folders/6r/rf3yfzqd6js8c1p3s7bmz5hc0000gn/T/tmp56w3cx48/plugin.zip/'
```

**Comment by raguay** [comment]
Hi, This error was upon installing. None of the plugin code is used during installation. Therefore, this is an fman problem and not a problem with my plugin. I'll copy it to the fman issues.

**Comment by raguay** [comment]
I added it here:  https://github.com/fman-users/fman/issues/257
